package sessiontext

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestIsBoilerplatePromptFlagsAllPrefixes(t *testing.T) {
	cases := []string{
		"# AGENTS.md instructions for /Users/me/Projects/foo",
		"<command-name>/model</command-name> <command-message>model</command-message>",
		"<command-args>--flag</command-args>",
		"<command-message>init</command-message>",
		"<system-reminder>This is automated.</system-reminder>",
		"<INSTRUCTIONS> # Global instructions",
		"<environment_context>cwd=/tmp</environment_context>",
		"<permissions instructions>only read</permissions instructions>",
		"<collaboration_mode>plan</collaboration_mode>",
		"<local-command-caveat>local cmd</local-command-caveat>",
		"You are Codex, a coding agent. Knowledge cutoff: 2025.",
		"Knowledge cutoff: 2025-04",
		// Leading whitespace shouldn't fool us.
		"   # AGENTS.md instructions for /tmp",
		"\n\t<command-name>/init</command-name>",
	}
	for _, in := range cases {
		t.Run(in[:min(40, len(in))], func(t *testing.T) {
			require.True(t, IsBoilerplatePrompt(in),
				"expected %q to be flagged as boilerplate", in)
		})
	}
}

func TestIsBoilerplatePromptKeepsRealPrompt(t *testing.T) {
	cases := []string{
		"refactor the sync logic so the reconcile is idempotent",
		"why is the timeline showing 165 rows?",
		"<other-tag>not on the list</other-tag>",
	}
	for _, in := range cases {
		t.Run(in[:min(40, len(in))], func(t *testing.T) {
			require.False(t, IsBoilerplatePrompt(in),
				"expected %q to NOT be flagged as boilerplate", in)
		})
	}
}

func TestCleanPromptStripsCaveatWrapper(t *testing.T) {
	in := "<local-command-caveat>Caveat: messages below were generated by the user " +
		"while running local commands.</local-command-caveat>\n\nrefactor the sync"
	out := CleanPrompt(in)
	require.Equal(t, "refactor the sync", out)
	require.False(t, IsBoilerplatePrompt(in),
		"caveat + real prompt should resolve to non-boilerplate")
}

func TestCleanPromptStripsChainedWrappers(t *testing.T) {
	in := "<command-name>/init</command-name>\n<command-args>--force</command-args>\n" +
		"do the thing"
	out := CleanPrompt(in)
	require.Equal(t, "do the thing", out)
}

func TestCleanPromptReturnsOriginalWhenAllMeta(t *testing.T) {
	in := "<command-name>/init</command-name>\n<command-args>--force</command-args>"
	out := CleanPrompt(in)
	require.Equal(t, in, out, "no human content remained; caller falls back to placeholder")
	require.True(t, IsBoilerplatePrompt(in))
}

func TestCleanPromptPassesThroughCleanInput(t *testing.T) {
	in := "explain quantum entanglement"
	require.Equal(t, in, CleanPrompt(in))
}

func TestCleanPromptReturnsOriginalForUnknownTag(t *testing.T) {
	in := "<not-on-the-list>hi</not-on-the-list>"
	require.Equal(t, in, CleanPrompt(in))
}

func TestFirstNonBoilerplateSkipsMetaCandidates(t *testing.T) {
	candidates := []string{
		"You are Codex, a coding agent",
		"# AGENTS.md instructions for /tmp",
		"<system-reminder>auto</system-reminder>",
		"deploy the staging branch",
		"second real prompt that should not win",
	}
	require.Equal(t, "deploy the staging branch", FirstNonBoilerplate(candidates))
}

func TestFirstNonBoilerplateUnwrapsWhenNeeded(t *testing.T) {
	candidates := []string{
		"<local-command-caveat>auto</local-command-caveat>\nrun the migration",
	}
	require.Equal(t, "run the migration", FirstNonBoilerplate(candidates))
}

func TestFirstNonBoilerplateEmptyOnAllMeta(t *testing.T) {
	candidates := []string{
		"You are Codex, a coding agent",
		"<system-reminder>auto</system-reminder>",
	}
	require.Equal(t, "", FirstNonBoilerplate(candidates))
}

func TestFirstNonBoilerplateEmptyInput(t *testing.T) {
	require.Equal(t, "", FirstNonBoilerplate(nil))
	require.Equal(t, "", FirstNonBoilerplate([]string{}))
	require.Equal(t, "", FirstNonBoilerplate([]string{"", "  "}))
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
