export { buildApp, type BuildAppOptions } from './app.js'
export { loadConfig, ConfigError, type ProsaApiConfig } from './config.js'
export { appRouter, type AppRouter } from './trpc/router.js'
export type { ProsaApiContext } from './trpc/context.js'
export { readPackageVersion } from './version.js'
